#!/bin/sh
xrdb /home/viacheslav/.Xresources
setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"
#fix GTK problems
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
exec qtile start
